### ISSUE TITLE
access array item by index

### ISSUE THREAD

**Issue by gibatronic** [mustache/mustache#188]
hi! is there a way to access an array item by its index position? this way it doesn't seems to work: 

```ruby
require 'mustache'

data = {
  collection: [{
    title: 'one'
  }, {
    title: 'two'
  }, {
    title: 'three'
  }]
}

template = '{{collection.0.title}}'

puts Mustache.render template, data
```

I expect `one` to be printed, but I only get an empty string.

**Comment by locks** [comment]
Hello!
As far as I know that syntax is not valid per Mustache spec, so it is not implemented.

**Comment by bobthecow** [comment]
@locks It's not invalid, either.

This is more of an "implementations should do what makes sense in the host language" sort of call. In PHP and JavaScript, this…

```
$collection[0]['title']
```

is how you would access the title property of the first value in an array called `$collection`. This…

```
$collection[0]['title']
```

… is how you'd access the title property of the value at the '0' key of a hash called `$collection`.

So in both of those languages, it would be surprising if you *couldn't* access array elements by index.

**Comment by locks** [comment]
So that template works in mustache.php?

**Comment by bobthecow** [comment]
Yep. And mustache.js

**Comment by locks** [comment]
Hm.

**Comment by bobthecow** [comment]
I wouldn't *recommend* it, since accessing things by array index feels like it violates the spirit of mustache to me. But it's possible :)

**Comment by gibatronic** [comment]
hm... okay then! thanks guys! I'll parse it before hand and give everything ready to Mustache.
