### ISSUE TITLE
Caching template creation

### ISSUE THREAD

**Issue by KillaPL** [mustache/mustache#193]
Hi. Based on my pull request I'm exploring further options for improvements. My friend noticed this: https://gist.github.com/jaen/9bede63d9b6bbc494810

The biggest problem appears to be compiling the templates all over again, not rendering.

Maybe we could cache compiled templates on some global level based on templates (string) #hash result?
Then we would just compile it once and that's it. I would be happy to try implementing this.

**Comment by locks** [comment]
Related: https://github.com/mustache/mustache/pull/173

**Comment by KillaPL** [comment]
Very well, you can close the issue. I will look for performance improvements elsewhere.
