### ISSUE TITLE
Mustache::Utils::String

### ISSUE THREAD

**Issue by KillaPL** [mustache/mustache#194]
Mustache class has way too much responsibilities, including string transformation. What do you think about introducing 

    Mustache::Utils::String

Which would be composed of string and implement transformation code? Much like https://github.com/lotus/utils/blob/master/lib/lotus/utils/string.rb

This would make the responsibilities more clear and easier to understand.

**Comment by locks** [comment]
@KillaPL check what you think of 
https://github.com/mustache/mustache/commit/3d821767050568b98d14fbc2dbf3697726fa7bb0 .
I'm not sure this is going to stay as-is (seems excessive to create a new object every time you want to do one of them), but it's a first step :P

**Comment by KillaPL** [comment]
I was thinking about removing self.classify and self.underscore completely, just so Mustache class is smaller. Would you mind looking a little bit into https://github.com/lotus/lotus and it's dependencies? I see a lot of place for improvements in Mustache's codebase and if we can agree on some common ground, I'd be happy to spend some time here for fun.

**Comment by KillaPL** [comment]
Also, there is no need to be worried about object creation in this case. Objects are spammed with hundreds of thousands in other places, I'm working on some benchmarks: ]. This: https://github.com/mustache/mustache/issues/195 Would remove much more objects from being created than having to create Utils::String adds.
