### ISSUE TITLE
Question about html escaping

### ISSUE THREAD

**Issue by KillaPL** [mustache/mustache#195]
If I understand it correctly, it is possible to overwrite how mustache escapes htmls but overwriting

    class Mustache
      def escapeHTML(str)
        CGI.escapeHTML(str)
      end
    end

However, a really big problem with this approach is, that Mustache object has to be looked up in Mustache::Context#escapeHTML in order to perform this. This lookup, even cached, is very expensive.
Removing the lookup results in around 20% quicker render and 9% less objects created in quickly created benchmark.

Another solution for allowing the escape overwrite is to create a class like this:

    class Mustache
      class Escaper
        def escape(string)
          CGI.escapeHTML(string)
        end
      end
    end

This solution still allows for overwriting escaping method globally, reduces Mustache class responsibilities and removes the costly lookup.

Would that be a change you're willing to introduce?

**Comment by KillaPL** [comment]
Using the benchmark commited in https://github.com/mustache/mustache/commit/8f36b3885479e63a61ad9302db4957015ba7a16b

the gain is somewhere around this:

    BEFORE
    Calculating -------------------------------------
       render list of 10   160.000  i/100ms
      render list of 100    71.000  i/100ms
     render list of 1000    10.000  i/100ms
    -------------------------------------------------
       render list of 10    259.678k (± 6.6%) i/s -      1.284M
      render list of 100     51.336k (± 5.5%) i/s -    255.103k
     render list of 1000      1.076k (± 7.1%) i/s -      5.350k

    AFTER
    Calculating -------------------------------------
       render list of 10   167.000  i/100ms
      render list of 100    81.000  i/100ms
     render list of 1000    12.000  i/100ms
    -------------------------------------------------
       render list of 10    277.827k (± 6.4%) i/s -      1.375M
      render list of 100     65.332k (± 8.6%) i/s -    322.380k
     render list of 1000      1.562k (± 6.7%) i/s -      7.776k

So, almost 7% for small collections, 27% speedup in code I expect to be rendering myself, up to 50% in rendering big collections. Piece by piece we can get quite a significant speedup this way : )

**Comment by locks** [comment]
Hm, this means changing the public API correct?

**Comment by KillaPL** [comment]
We can do

    class Mustache
      class Escaper
        def escape(string)
          Mustache.escapeHTML(string)
        end
      end
    end

and in Mustache.escapeHTML write a deprecation warning.

**Comment by KillaPL** [comment]
@locks I also found out, that CGI is rather slow solution. Using https://github.com/brianmario/escape_utils instead has this effect:



    BEFORE
    Calculating -------------------------------------
    render template without escaping
                            10.192k i/100ms
    render template with escaping
                             4.931k i/100ms
    -------------------------------------------------
    render template without escaping
                              1.056B (±11.8%) i/s -      4.529B
    render template with escaping
                            250.615M (±13.2%) i/s -      1.137B

    AFTER
    Calculating -------------------------------------
    render template without escaping
                            10.812k i/100ms
    render template with escaping
                             9.649k i/100ms
    -------------------------------------------------
    render template without escaping
                              1.206B (±12.3%) i/s -      5.112B
    render template with escaping
                            957.249M (±13.0%) i/s -      4.098B

So it's always measurably faster and we have no code to add other than include the gem.

**Comment by locks** [comment]
That library seems to use C extensions, which worries me.

**Comment by KillaPL** [comment]
We can require it conditionally and let java people not use it: ]

**Comment by hugopeixoto** [comment]
@KillaPL with that change you would still need to instantiate the Escape object somewhere.
Did you mean to create a class method instead?

    class Mustache
      class Escaper
        def self.escape(str)
          CGI.escapeHTML(str)
        end
      end
    end

**Comment by KillaPL** [comment]
Class methods are ugly and not object oriented. I was actually thinking about a singleton class with regular method. Even if it's a regular class, having to create it is nowhere near as expensive as the lookup it forces to make.

**Comment by hugopeixoto** [comment]
I was just making sure I understood what you meant.

Using that approach would remove functionality, as right now you can redefine the escaping policy in different contexts. An example would be using a template inside a script tag, where you shouldn't generate html entities. I'm not sure if people actually use this feature in any way, but I guess it may break previous usage.

The lookup mechanism is not only used for the escaping policy, although it is probably causes it to be used all the time. Maybe there's a way to simplify this so that looking up the current mustache object is straightforward. The whole context management looks a bit weird right now.

**Comment by KillaPL** [comment]
> I'm not sure if people actually use this feature in any way

I see the reasoning, but I'm not sure if this is something anyone would actually do...

> but I guess it may break previous usage.

What I'm trying to suggest is moving heavily for performance. It's, actually, rather terrible, especially that mustache is rather simple template language.

> The whole context management looks a bit weird right now.

It is, I'm trying to suggest changes which would not result in general rewrite. Unless general rewrite is on the table.

**Comment by locks** [comment]
A rewrite (2.0) isn't completely off the table, but they're hard to pull off for various reasons, like people dropping off the project, me having to review a truckload of code, etc.
Where possible, changes without impacting the public API, including loss of features, would be best.

**Comment by KillaPL** [comment]
We could incrementally implement braking features and call it 2.0 at some point. Can I start issue about this and discuss some ideas of mine? This single issue is about html escaping; )

**Comment by bobthecow** [comment]
You can't do that if you're going to follow SemVer (which most developers assume you're doing, because what are you, a sociopath?)

**Comment by locks** [comment]
This thread is leaving me worried.
Can you go to mustache's gitter sometime so we can discuss it better?
