### ISSUE TITLE
No documentation on $ tag

### ISSUE THREAD

**Issue by timgent** [mustache/mustache#213]
I came across the $ operator in someone else's code, but couldn't find any mention of this tag in the docs. However there was something in this pull request:

https://github.com/mustache/spec/pull/75

Would be really helpful to have this added to the docs:
https://mustache.github.io/mustache.5.html

**Comment by locks** [comment]
This implementation does not support template inheritance, that is why it's not documented.
It seems that extension is also not quite official yet, as it hasn't been merged.

**Comment by bobthecow** [comment]
Several mustache implementations have implemented template inheritance as specified in mustache/spec#75 (php, hogan, java, iirc?). Additionally, GRMustache implemented a superset of it. At this point, think of it as vendor-prefixed css properties. It'll probably end up in the spec at some point, but it might not look exactly like what is currently implemented :)
