### ISSUE TITLE
"empty semantic" classic problem, need an elegant solution

### ISSUE THREAD

**Issue by ppKrauss** [mustache/mustache#230]
The ambition of dealing with various languages has its cost: the "empty string as false" is not an universal standard, even  among JSON users...  So, the Mustache user need a some control about it. How to set  the "empty semantic" in Mustache? 

The issue #47 was a good idea (!), there are an elegant alternative to it?

**Comment by locks** [comment]
Can you move this discussion over to https://github.com/mustache/spec/issues ? Thank you!
