### ISSUE TITLE
Syntax idea: "{{key?}}" for checking whether "key" is non-empty

### ISSUE THREAD

**Issue by mislav** [mustache/mustache#47]
I'm hitting a repetitive and tedious pattern while writing mustache templates. Let me explain.

First of all, let me state that I absolutely love the lists sections feature of mustache (example taken from man page):

```
{{#repo}}
  <b>{{name}}</b>
{{/repo}}

<b>resque</b>
<b>hub</b>
<b>rip</b>
```

However, in HTML, lists are usually, well, _lists_. And chances are they are a part of some context. Real-world example:

```
<h2>Related posts:</h2>

<ul>
  {{#related_posts}}
  <li>{{ title }}</li>
  {{/related_posts}}
</ul>
```

Now, the pattern I mentioned starts to arise when handling empty lists. In the last example, an empty list would still render the H2 and empty UL tags. We have to write a new section to encompass the context of related posts:

```
{{#has_related_posts}}
<h2>Related posts:</h2>
<ul>...</ul>
{{/has_related_posts}}
```

And we have to get back to the view and actually implement the "has_related_posts" key/method. In ruby Mustache views, I regularly finish up with a bunch of these extra methods all sharing a similar implementation: checking for `list.empty?`.

My idea for a new syntax to eliminated this pattern is this:

```
{{#related_posts?}}
<h2>Related posts:</h2>
<ul>...</ul>
{{/related_posts?}}
```

If the "related_posts?" key/method doesn't exist, mustache would check "related_posts" and return true for non-blank values. In short, adding a question mark to the end would ensure that a boolean is returned. Empty lists would always be false, empty strings might too (like ActiveSupport `blank?` semantics).

The man page already has an example of using keys that end with a question mark:

```
{
  "person?": { "name": "Jon" }
}
```

I don't think this is a very good example of some best practice; the question mark here is entirely superfluous. Mustache has the opportunity to declare some semantics for the question mark, same as in Ruby language.

The question remains whether this warrants extending the spec? Because this behavior could, theoretically, be implemented entirely in the view—in Ruby it could be powered by method_missing. Other implementations could, when sending a hash of key-value pairs for rendering, make an additional pass and add extra boolean values for each of the existing keys. All this is definitely possible for the user—I'm just wondering if it would be a good idea for the spec.

**Comment by boblail** [comment]
+1
